/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ConferenciaRouteImport } from './routes/conferencia'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecebimentosIndexRouteImport } from './routes/recebimentos.index'
import { Route as RecebimentosIdRouteImport } from './routes/recebimentos.$id'

const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenciaRoute = ConferenciaRouteImport.update({
  id: '/conferencia',
  path: '/conferencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentosIndexRoute = RecebimentosIndexRouteImport.update({
  id: '/recebimentos/',
  path: '/recebimentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentosIdRoute = RecebimentosIdRouteImport.update({
  id: '/recebimentos/$id',
  path: '/recebimentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/auth': typeof AuthRoute
  '/conferencia': typeof ConferenciaRoute
  '/inventario': typeof InventarioRoute
  '/recebimentos/$id': typeof RecebimentosIdRoute
  '/recebimentos/': typeof RecebimentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/auth': typeof AuthRoute
  '/conferencia': typeof ConferenciaRoute
  '/inventario': typeof InventarioRoute
  '/recebimentos/$id': typeof RecebimentosIdRoute
  '/recebimentos': typeof RecebimentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/auth': typeof AuthRoute
  '/conferencia': typeof ConferenciaRoute
  '/inventario': typeof InventarioRoute
  '/recebimentos/$id': typeof RecebimentosIdRoute
  '/recebimentos/': typeof RecebimentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/auth'
    | '/conferencia'
    | '/inventario'
    | '/recebimentos/$id'
    | '/recebimentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/auth'
    | '/conferencia'
    | '/inventario'
    | '/recebimentos/$id'
    | '/recebimentos'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/auth'
    | '/conferencia'
    | '/inventario'
    | '/recebimentos/$id'
    | '/recebimentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  AuthRoute: typeof AuthRoute
  ConferenciaRoute: typeof ConferenciaRoute
  InventarioRoute: typeof InventarioRoute
  RecebimentosIdRoute: typeof RecebimentosIdRoute
  RecebimentosIndexRoute: typeof RecebimentosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferencia': {
      id: '/conferencia'
      path: '/conferencia'
      fullPath: '/conferencia'
      preLoaderRoute: typeof ConferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimentos/': {
      id: '/recebimentos/'
      path: '/recebimentos'
      fullPath: '/recebimentos/'
      preLoaderRoute: typeof RecebimentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimentos/$id': {
      id: '/recebimentos/$id'
      path: '/recebimentos/$id'
      fullPath: '/recebimentos/$id'
      preLoaderRoute: typeof RecebimentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  AuthRoute: AuthRoute,
  ConferenciaRoute: ConferenciaRoute,
  InventarioRoute: InventarioRoute,
  RecebimentosIdRoute: RecebimentosIdRoute,
  RecebimentosIndexRoute: RecebimentosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
